### ISSUE TITLE
mainline 10"

### ISSUE THREAD

**Issue by bereket8** [antonialoytorrens/SGalaxy-Tab2-linux-images#1]
I've galaxy tab 2 10" 3G. i don't know if you need device to test mainline with. i could help testing

**Comment by MightyM17** [comment]
Hi there! Glad you would like to help us with mainline :D.
The 10 inch model has different display, touchscreen and few sensors (also what model do you have?)
I got the display working but didnt get much time to work on touchscreen, you could help us there as well :D

Do you have any experience with building linux and so on?

**Comment by antonialoytorrens** [comment]
The device should have support in https://wiki.postmarketos.org/wiki/Samsung_Galaxy_Tab_2_10.1_(3G_and_Wifi)_(samsung-espresso10) .

As I don't have the device, you may need to do everything from scratch, as seen here: https://github.com/antonialoytorrens/SGalaxy-Tab2-linux-images#doing-everything-from-scratch
