### ISSUE TITLE
P3310 doesn't loads desktop manager

### ISSUE THREAD

**Issue by Ananadss** [antonialoytorrens/SGalaxy-Tab2-linux-images#3]
I use a espressowifi, and when my tablet turns off, after loading a desktop manager doesnt load,  So now, I haven't found a way to fix this other than re-flashing a tablet
![1731346654801509670471615544231](https://github.com/user-attachments/assets/dbf97025-189f-4859-962d-c76e8e1aea28)

**Comment by MightyM17** [comment]
Nothing out of the usual except the EXT4 errors, could you by any chance grab entire dmesg?

**Comment by Ananadss** [comment]
> Nothing out of the usual except the EXT4 errors, could you by any chance grab entire dmesg?

Unfortunately, I can't. but after the label “welcome to postmarketos” errors are displayed regarding the creation of the log (read-only file system) the system is installed on the mmcblk0p10 block (FACTORYFS)

**Comment by MightyM17** [comment]
Seems like some kind of emmc bug, our device is known to have emmc issues. Id suggest moving to a sdcard installation but no clue on how you'll the data back from this

**Comment by Ananadss** [comment]
> Seems like some kind of emmc bug, our device is known to have emmc issues. Id suggest moving to a sdcard installation but no clue on how you'll the data back from this

I have an empty 2GB memory card, is it enough for the system?

**Comment by MightyM17** [comment]
Depending on your use case, I suppose a base installation with phosh ui is possible

**Comment by Ananadss** [comment]
> Depending on your use case, I suppose a base installation with phosh ui is possible

yes, I'll use the phosh

**Comment by MightyM17** [comment]
> > Depending on your use case, I suppose a base installation with phosh ui is possible
> 
> yes, I'll use the phosh

What other applications do ya use?

**Comment by Ananadss** [comment]
> > > Depending on your use case, I suppose a base installation with phosh ui is possible
> > 
> > 
> > yes, I'll use the phosh
> 
> What other applications do ya use?

 I don't use any applications other than the basic ones, except for hwinfo and neofetch

**Comment by MightyM17** [comment]
You should be fine with 2gb

**Comment by Ananadss** [comment]
> You should be fine with 2gb

 is it possible to install this without using pmbootstrap? my wsl is not working and because of that i cant use or create the needed files

**Comment by MightyM17** [comment]
> > You should be fine with 2gb
> 
> is it possible to install this without using pmbootstrap? my wsl is not working and because of that i cant use or create the needed files

Uh i am not sure how, you can try flashing img on sdcard on windows, but thats just more work. Maybe we could work on fixing wsl?

**Comment by Ananadss** [comment]
> > > You should be fine with 2gb
> > 
> > 
> > is it possible to install this without using pmbootstrap? my wsl is not working and because of that i cant use or create the needed files
> 
> Uh i am not sure how, you can try flashing img on sdcard on windows, but thats just more work. Maybe we could work on fixing wsl?

I'll have the laptop with card adapter and lubuntu live usb, is that enough to flash image? and i can't find any information about my error with wsl: when i try to enable virtual machine platform, i get an error, using dism via administrator doesn't work

**Comment by MightyM17** [comment]
Oh no clue about that, and yes a live usb should be fine, just make sure u have enough storage in it (or put pmaports in your hard disk partition)

**Comment by Ananadss** [comment]
> Oh no clue about that, and yes a live usb should be fine, just make sure u have enough storage in it (or put pmaports in your hard disk partition)

I`ll have the better solution, using virtualbox and linux image, but when i start pmbootstrap, i have this: 
![image](https://github.com/user-attachments/assets/10684eff-ffbb-459c-b498-b040988f18a0)

**Comment by MightyM17** [comment]
https://wiki.postmarketos.org/wiki/Pmbootstrap#From_git
Are you following this?

**Comment by Ananadss** [comment]
> https://wiki.postmarketos.org/wiki/Pmbootstrap#From_git Are you following this?

Yes

**Comment by MightyM17** [comment]
Try linking it in /bin like it says with that path

**Comment by Ananadss** [comment]
> Try linking it in /bin like it says with that path

 I checked everything, and apparently the problem is in the python file, which does not see the library needed

**Comment by MightyM17** [comment]
Wrong python version? 
Better ask in the pmOS matrix/irc channels

**Comment by Ananadss** [comment]
> Wrong python version? Better ask in the pmOS matrix/irc channels

So, I find the solution, just creating one sh file, what corrects some settings when system is booting, thanks for trying to help me.

**Comment by MightyM17** [comment]
> > Wrong python version? Better ask in the pmOS matrix/irc channels
> 
> So, I find the solution, just creating one sh file, what corrects some settings when system is booting, thanks for trying to help me.

That's great! Can you share the solution for others if they seems to face the same issue

**Comment by Ananadss** [comment]
> > > Wrong python version? Better ask in the pmOS matrix/irc channels
> > 
> > 
> > So, I find the solution, just creating one sh file, what corrects some settings when system is booting, thanks for trying to help me.
> 
> That's great! Can you share the solution for others if they seems to face the same issue

This is written in pmos wiki, you need create a .sh file in `/etc/tinydm.d/env-wayland.d/ ` in mounted postmarketos rootfs, and add the following text:
 `export MESA_LOADER_DRIVER_OVERRIDE=pvr`
This works for Phosh, and maybe other wayland based desktops
